### ISSUE TITLE
Exam Details Page

### ISSUE THREAD

**Issue by Enjoyisgood** [Esayf/examina-mono#1]
Requirements:
Name
Description
Start Date
Duration
Status : Upcoming, Ongoing, On Review, Past,
Type: Public, Private
Button : Join Exam(If upcoming and user and not creator and PRIVATE (WIP)), Start Exam (if ongoing and user and not creator), Finish Exam (if on review and only creator)
Check Score
Total participants : number

**Comment by BlocksOnChain** [comment]
20 March 23:59 (With refactors on bugs)
